name: Build DEV version
on:
  workflow_dispatch:

jobs:
  build-image-container:
    name: BUILD
    uses: Cloud-for-You/github-workflows/.github/workflows/build-go-container.yaml@main
    secrets: inherit